Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,9 +65,10 @@ jobs:
               
       - name: Check generated files
         run: |
-          if [ ! -f *.xml ]; then
-            echo "No XML files generated."
-            exit 1
+          xml_count=$(find . -maxdepth 1 -name "*.xml" | wc -l)
+          if [ "$xml_count" -eq 0 ]; then
+          echo "::error::No XML files generated"
+          exit 1
           fi
 
       - name: Clean up old deployment
